# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - uses: actions/setup-node@v1.1.0
      with: 
        version: 11.x 
    - name: Start Ground Server
      run: |
        python3 -m venv venv; source venv/bin/activate
        pip install -r requirements.txt
        python main.py
    - name: Start ElasticSearch
      run: |
        elasticsearch
    - name: Start MCT
      run: |
        npm install
        npm test
